# Autogenerated by nbdev

d = { 'settings': {'branch': '', 'doc_baseurl': '/', 'doc_host': 'https://.github.io', 'git_url': 'https://github.com//', 'lib_path': ''},
  'syms': {'demo3.core': {'demo3.core.hello': ('create.html#hello', 'demo3/core.py')}, 'demo3.setup': {}}}
